import React, { useState } from "react";
import { View, Text, TouchableOpacity, StyleSheet } from "react-native";
import { useOnboardingStore } from "../store";
import type { NativeStackScreenProps } from "@react-navigation/native-stack";
import type { RootStackParamList } from "../../types/navigation";
import type { HandSide } from "../../types";
import { useAppTheme } from "../theme/useAppTheme";
import { Ionicons } from "@expo/vector-icons";

type Props = NativeStackScreenProps<RootStackParamList, "Onboarding">;

type Step = "welcome" | "disclaimer" | "hand" | "permission";

export function OnboardingScreen({ navigation }: Props) {
  const { colors, isDark } = useAppTheme();
  
  const [step, setStep] = useState<Step>("welcome");
  const setHandChoice = useOnboardingStore((s) => s.setHandChoice);
  const setCompleted = useOnboardingStore((s) => s.setCompleted);

  const handleNext = () => {
    if (step === "welcome") setStep("disclaimer");
    else if (step === "disclaimer") setStep("hand");
    else if (step === "hand") setStep("permission");
    else {
      setCompleted(true);
      navigation.replace("Main");
    }
  };

  const handleHandChoice = (side: HandSide, dominant: boolean) => {
    setHandChoice(side, dominant);
    setStep("permission");
  };

  return (
    <View style={[styles.container, { backgroundColor: colors.background }]}>
      {/* Progress indicator */}
      <View style={styles.progressContainer}>
        <View style={[styles.progressDot, { backgroundColor: colors.surfaceElevated }, step === "welcome" && { backgroundColor: colors.accent, width: 24 }]} />
        <View style={[styles.progressDot, { backgroundColor: colors.surfaceElevated }, step === "disclaimer" && { backgroundColor: colors.accent, width: 24 }]} />
        <View style={[styles.progressDot, { backgroundColor: colors.surfaceElevated }, step === "hand" && { backgroundColor: colors.accent, width: 24 }]} />
        <View style={[styles.progressDot, { backgroundColor: colors.surfaceElevated }, step === "permission" && { backgroundColor: colors.accent, width: 24 }]} />
      </View>

      {step === "welcome" && (
        <View style={styles.content}>
          {/* App Icon */}
          <View style={[styles.iconContainer, { backgroundColor: colors.surfaceElevated, borderColor: colors.border, shadowColor: colors.accent }]}>
             <Ionicons name="sparkles" size={64} color={colors.accent} />
          </View>
          
          <Text style={[styles.title, { color: colors.textPrimary }]} accessibilityRole="header">
            Cosmic Palmistry
          </Text>
          <Text style={[styles.description, { color: colors.muted }]}>
            Unveil the secrets written in your hands through the power of ancient wisdom and modern AI.
          </Text>
          <TouchableOpacity
            style={[styles.button, { backgroundColor: colors.accent, shadowColor: colors.accent }]}
            onPress={handleNext}
            accessibilityLabel="Continue to disclaimer"
            accessibilityRole="button"
          >
            <Text style={[styles.buttonText, { color: isDark ? colors.background : "#1F2937" }]}>Begin Journey</Text>
            <Ionicons name="arrow-forward" size={20} color={isDark ? colors.background : "#1F2937"} style={{marginLeft: 8}} />
          </TouchableOpacity>
        </View>
      )}
      
      {step === "disclaimer" && (
        <View style={styles.content}>
          <View style={[styles.iconContainer, { backgroundColor: colors.surfaceElevated, borderColor: colors.border, shadowColor: colors.accent }]}>
            <Ionicons name="alert-circle-outline" size={64} color={colors.accent} />
          </View>
          <Text style={[styles.title, { color: colors.textPrimary }]} accessibilityRole="header">
            Disclaimer
          </Text>
          <Text style={[styles.description, { color: colors.muted }]}>
            This app is for entertainment and self-reflection only. Insights are interpretive and generated by AI.
            Please treat them as creative cosmic guidance, not absolute fact.
          </Text>
          <TouchableOpacity
            style={[styles.button, { backgroundColor: colors.accent, shadowColor: colors.accent }]}
            onPress={handleNext}
            accessibilityLabel="I understand, continue"
            accessibilityRole="button"
          >
            <Text style={[styles.buttonText, { color: isDark ? colors.background : "#1F2937" }]}>I Understand</Text>
          </TouchableOpacity>
        </View>
      )}
      
      {step === "hand" && (
        <View style={styles.content}>
          <Text style={[styles.title, { color: colors.textPrimary }]} accessibilityRole="header">
            Choose Your Hand
          </Text>
          <Text style={[styles.description, { color: colors.muted }]}>
            Select your dominant hand (the one you write with) for the most accurate reading of your potential.
          </Text>
          <View style={styles.handChoices}>
            <TouchableOpacity
              style={[styles.handButton, { backgroundColor: colors.surface, borderColor: colors.border }]}
              onPress={() => handleHandChoice("left", true)}
              accessibilityRole="button"
              accessibilityLabel="Left hand, dominant"
            >
              <Ionicons name="hand-left" size={48} color={colors.accent} style={{marginBottom: 12}} />
              <Text style={[styles.handText, { color: colors.textPrimary }]}>Left Hand</Text>
              <Text style={[styles.handSubtext, { color: colors.muted }]}>Dominant</Text>
            </TouchableOpacity>
            <TouchableOpacity
              style={[styles.handButton, { backgroundColor: colors.surface, borderColor: colors.border }]}
              onPress={() => handleHandChoice("right", true)}
              accessibilityRole="button"
              accessibilityLabel="Right hand, dominant"
            >
              <Ionicons name="hand-right" size={48} color={colors.accent} style={{marginBottom: 12}} />
              <Text style={[styles.handText, { color: colors.textPrimary }]}>Right Hand</Text>
              <Text style={[styles.handSubtext, { color: colors.muted }]}>Dominant</Text>
            </TouchableOpacity>
          </View>
          <TouchableOpacity style={styles.skipButton} onPress={handleNext}>
            <Text style={[styles.skipText, { color: colors.textDim }]}>Skip & decide later</Text>
          </TouchableOpacity>
        </View>
      )}
      
      {step === "permission" && (
        <View style={styles.content}>
          <View style={[styles.iconContainer, { backgroundColor: colors.surfaceElevated, borderColor: colors.border, shadowColor: colors.accent }]}>
            <Ionicons name="camera-outline" size={64} color={colors.accent} />
          </View>
          <Text style={[styles.title, { color: colors.textPrimary }]} accessibilityRole="header">
            Camera Access
          </Text>
          <Text style={[styles.description, { color: colors.muted }]}>
            We need access to your camera to capture your palm lines. 
            Your images are analyzed securely and stored only on your device.
          </Text>
          <TouchableOpacity
            style={[styles.button, { backgroundColor: colors.accent, shadowColor: colors.accent }]}
            onPress={handleNext}
            accessibilityLabel="Continue to app"
            accessibilityRole="button"
          >
            <Text style={[styles.buttonText, { color: isDark ? colors.background : "#1F2937" }]}>Enable Camera</Text>
          </TouchableOpacity>
        </View>
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: 24,
    justifyContent: "center",
    alignItems: "center",
  },
  content: {
    width: "100%",
    alignItems: "center",
  },
  iconContainer: {
    width: 120,
    height: 120,
    borderRadius: 60,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 32,
    borderWidth: 1,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.2,
    shadowRadius: 20,
  },
  title: {
    fontSize: 28,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 16,
  },
  description: {
    fontSize: 15,
    textAlign: "center",
    lineHeight: 24,
    marginBottom: 40,
    maxWidth: 300,
  },
  button: {
    paddingVertical: 16,
    paddingHorizontal: 32,
    borderRadius: 30,
    minWidth: 200,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
  },
  buttonText: {
    fontSize: 16,
    fontWeight: "bold",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  handChoices: {
    flexDirection: "row",
    gap: 16,
    marginBottom: 24,
    width: "100%",
  },
  handButton: {
    flex: 1,
    borderRadius: 20,
    padding: 24,
    alignItems: "center",
    borderWidth: 1,
    minHeight: 160,
    justifyContent: "center",
  },
  handText: {
    fontSize: 16,
    fontWeight: "700",
    marginBottom: 4,
  },
  handSubtext: {
    fontSize: 12,
  },
  skipButton: {
    paddingVertical: 12,
  },
  skipText: {
    fontSize: 14,
  },
  progressContainer: {
    flexDirection: "row",
    gap: 8,
    position: "absolute",
    bottom: 50,
  },
  progressDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
});
