import React, { useState } from "react";
import { View, Text, TouchableOpacity, StyleSheet, Image } from "react-native";
import { useOnboardingStore } from "../store";
import type { NativeStackScreenProps } from "@react-navigation/native-stack";
import type { RootStackParamList } from "../../types/navigation";
import type { HandSide } from "../../types";

type Props = NativeStackScreenProps<RootStackParamList, "Onboarding">;

type Step = "welcome" | "disclaimer" | "hand" | "permission";

export function OnboardingScreen({ navigation }: Props) {
  const [step, setStep] = useState<Step>("welcome");
  const setHandChoice = useOnboardingStore((s) => s.setHandChoice);
  const setCompleted = useOnboardingStore((s) => s.setCompleted);

  const handleNext = () => {
    if (step === "welcome") setStep("disclaimer");
    else if (step === "disclaimer") setStep("hand");
    else if (step === "hand") setStep("permission");
    else {
      setCompleted(true);
      navigation.replace("Main");
    }
  };

  const handleHandChoice = (side: HandSide, dominant: boolean) => {
    setHandChoice(side, dominant);
    setStep("permission");
  };

  return (
    <View style={styles.container}>
      {step === "welcome" && (
        <>
          {/* App Icon */}
          <Image
            source={require("../../../assets/icon.png")}
            style={styles.icon}
            resizeMode="contain"
          />
          
          <Text style={styles.title} accessibilityRole="header">
            Welcome to AI Palm Reading
          </Text>
          <Text style={styles.description}>
            Discover insights from your palm through ancient palmistry powered by modern AI.
            For reflection and curiosity.
          </Text>
          <TouchableOpacity
            style={styles.button}
            onPress={handleNext}
            accessibilityLabel="Continue to disclaimer"
            accessibilityRole="button"
          >
            <Text style={styles.buttonText}>Get Started</Text>
          </TouchableOpacity>
        </>
      )}
      
      {step === "disclaimer" && (
        <>
          <Text style={styles.emoji}>⚠️</Text>
          <Text style={styles.title} accessibilityRole="header">
            Disclaimer
          </Text>
          <Text style={styles.description}>
            This app is for entertainment and self-reflection. It does not predict the future. 
            Insights are interpretive and for fun. Results are generated by AI and should be 
            taken as creative interpretations only.
          </Text>
          <TouchableOpacity
            style={styles.button}
            onPress={handleNext}
            accessibilityLabel="I understand, continue"
            accessibilityRole="button"
          >
            <Text style={styles.buttonText}>I Understand</Text>
          </TouchableOpacity>
        </>
      )}
      
      {step === "hand" && (
        <>
          <Text style={styles.emoji}>✋</Text>
          <Text style={styles.title} accessibilityRole="header">
            Which hand would you like to read?
          </Text>
          <Text style={styles.description}>
            Choose your dominant hand (the one you write with) for insights about your present and future.
          </Text>
          <View style={styles.handChoices}>
            <TouchableOpacity
              style={styles.handButton}
              onPress={() => handleHandChoice("left", true)}
              accessibilityRole="button"
              accessibilityLabel="Left hand, dominant"
            >
              <Text style={styles.handEmoji}>🖐️</Text>
              <Text style={styles.handText}>Left Hand</Text>
              <Text style={styles.handSubtext}>Dominant</Text>
            </TouchableOpacity>
            <TouchableOpacity
              style={styles.handButton}
              onPress={() => handleHandChoice("right", true)}
              accessibilityRole="button"
              accessibilityLabel="Right hand, dominant"
            >
              <Text style={styles.handEmoji}>🤚</Text>
              <Text style={styles.handText}>Right Hand</Text>
              <Text style={styles.handSubtext}>Dominant</Text>
            </TouchableOpacity>
          </View>
          <TouchableOpacity style={styles.skipButton} onPress={handleNext}>
            <Text style={styles.skipText}>Skip for now</Text>
          </TouchableOpacity>
        </>
      )}
      
      {step === "permission" && (
        <>
          <Text style={styles.emoji}>📸</Text>
          <Text style={styles.title} accessibilityRole="header">
            Camera Access
          </Text>
          <Text style={styles.description}>
            We need camera access to capture your palm photo. Your photo is analyzed by AI 
            and stored locally on your device only. We never upload your images to any server.
          </Text>
          <TouchableOpacity
            style={styles.button}
            onPress={handleNext}
            accessibilityLabel="Continue to app"
            accessibilityRole="button"
          >
            <Text style={styles.buttonText}>Continue</Text>
          </TouchableOpacity>
        </>
      )}
      
      {/* Progress indicator */}
      <View style={styles.progressContainer}>
        <View style={[styles.progressDot, step === "welcome" && styles.progressDotActive]} />
        <View style={[styles.progressDot, step === "disclaimer" && styles.progressDotActive]} />
        <View style={[styles.progressDot, step === "hand" && styles.progressDotActive]} />
        <View style={[styles.progressDot, step === "permission" && styles.progressDotActive]} />
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#0f172a",
    paddingHorizontal: 24,
    paddingVertical: 60,
    justifyContent: "center",
    alignItems: "center",
  },
  icon: {
    width: 100,
    height: 100,
    marginBottom: 32,
  },
  emoji: {
    fontSize: 64,
    marginBottom: 24,
  },
  title: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#fff",
    textAlign: "center",
    marginBottom: 16,
  },
  description: {
    fontSize: 15,
    color: "#94a3b8",
    textAlign: "center",
    lineHeight: 22,
    marginBottom: 40,
  },
  button: {
    backgroundColor: "#9333ea",
    paddingVertical: 16,
    paddingHorizontal: 48,
    borderRadius: 12,
    minWidth: 200,
    alignItems: "center",
    shadowColor: "#9333ea",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
  },
  buttonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "700",
  },
  handChoices: {
    flexDirection: "row",
    gap: 16,
    marginBottom: 24,
    width: "100%",
  },
  handButton: {
    flex: 1,
    backgroundColor: "#1e293b",
    borderRadius: 16,
    padding: 24,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#334155",
    minHeight: 150,
    justifyContent: "center",
  },
  handEmoji: {
    fontSize: 48,
    marginBottom: 12,
  },
  handText: {
    fontSize: 16,
    fontWeight: "700",
    color: "#fff",
    marginBottom: 4,
  },
  handSubtext: {
    fontSize: 12,
    color: "#9333ea",
  },
  skipButton: {
    paddingVertical: 12,
  },
  skipText: {
    fontSize: 14,
    color: "#64748b",
    textDecorationLine: "underline",
  },
  progressContainer: {
    flexDirection: "row",
    gap: 8,
    position: "absolute",
    bottom: 40,
  },
  progressDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#334155",
  },
  progressDotActive: {
    backgroundColor: "#9333ea",
    width: 24,
  },
});
