import React from "react";
import { View, Text, ScrollView, Image, TouchableOpacity, StyleSheet } from "react-native";
import type { NativeStackScreenProps } from "@react-navigation/native-stack";
import type { HistoryStackParamList } from "../../types/navigation";

type Props = NativeStackScreenProps<HistoryStackParamList, "ReadingDetail">;

export function ReadingDetailScreen({ route, navigation }: Props) {
  const { reading } = route.params;

  const formatDate = (dateString: string) => {
    const date = new Date(dateString);
    return date.toLocaleDateString("en-US", {
      month: "long",
      day: "numeric",
      year: "numeric",
    });
  };

  const formatTime = (dateString: string) => {
    const date = new Date(dateString);
    return date.toLocaleTimeString("en-US", {
      hour: "2-digit",
      minute: "2-digit",
    });
  };

  return (
    <View style={styles.container}>
      {/* Header with Back Button */}
      <View style={styles.header}>
        <TouchableOpacity
          style={styles.backButton}
          onPress={() => navigation.goBack()}
          accessibilityRole="button"
          accessibilityLabel="Go back"
        >
          <Text style={styles.backButtonText}>←</Text>
        </TouchableOpacity>
        <View style={styles.headerContent}>
          <Text style={styles.headerTitle}>Palm Reading</Text>
        </View>
      </View>

      <ScrollView
        style={styles.scrollView}
        contentContainerStyle={styles.content}
        accessibilityLabel={`Reading for ${reading.handSide} hand`}
        showsVerticalScrollIndicator={false}
      >
        {/* Palm Image */}
        <View style={styles.imageContainer}>
          <Image
            source={{ uri: reading.imageUri }}
            style={styles.palmImage}
            resizeMode="cover"
          />
        </View>

        {/* Reading Info Card */}
        <View style={styles.infoCard}>
          <View style={styles.infoRow}>
            <View style={styles.infoItem}>
              <Text style={styles.infoLabel}>Hand</Text>
              <Text style={styles.infoValue}>
                {reading.handSide.charAt(0).toUpperCase() + reading.handSide.slice(1)}
              </Text>
            </View>
            <View style={styles.infoDivider} />
            <View style={styles.infoItem}>
              <Text style={styles.infoLabel}>Type</Text>
              <Text style={styles.infoValue}>
                {reading.isDominant ? "Dominant" : "Non-Dominant"}
              </Text>
            </View>
          </View>
          <View style={styles.dateRow}>
            <Text style={styles.dateText}>
              {formatDate(reading.createdAt)} • {formatTime(reading.createdAt)}
            </Text>
          </View>
        </View>

        {/* Reading Sections */}
        <Text style={styles.sectionsTitle}>Your Palm Reading</Text>
        {reading.sections.map((section, index) => (
          <View key={section.id} style={styles.section}>
            <View style={styles.sectionHeader}>
              <Text style={styles.sectionNumber}>
                {String(index + 1).padStart(2, "0")}
              </Text>
              <Text style={styles.sectionTitle}>{section.title}</Text>
            </View>
            <Text style={styles.sectionContent}>{section.content}</Text>
          </View>
        ))}

        {/* Footer Note */}
        <View style={styles.footer}>
          <Text style={styles.footerIcon}>🔮</Text>
          <Text style={styles.footerText}>
            This palm reading was generated by Gemini 3 Pro AI
          </Text>
          <Text style={styles.footerSubtext}>
            Analyzed on {formatDate(reading.createdAt)}
          </Text>
        </View>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#0f172a",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingTop: 60,
    paddingBottom: 16,
    backgroundColor: "#0f172a",
    borderBottomWidth: 1,
    borderBottomColor: "#334155",
  },
  backButton: {
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  backButtonText: {
    fontSize: 28,
    color: "#fff",
  },
  headerContent: {
    flex: 1,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#fff",
  },
  scrollView: {
    flex: 1,
  },
  content: {
    paddingBottom: 40,
  },
  imageContainer: {
    marginHorizontal: 16,
    marginTop: 16,
    marginBottom: 16,
    borderRadius: 16,
    overflow: "hidden",
    borderWidth: 2,
    borderColor: "#9333ea",
  },
  palmImage: {
    width: "100%",
    height: 300,
    backgroundColor: "#1e293b",
  },
  infoCard: {
    backgroundColor: "#1e293b",
    marginHorizontal: 16,
    marginBottom: 24,
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: "#334155",
  },
  infoRow: {
    flexDirection: "row",
    marginBottom: 16,
  },
  infoItem: {
    flex: 1,
    alignItems: "center",
  },
  infoLabel: {
    fontSize: 12,
    color: "#94a3b8",
    fontWeight: "600",
    marginBottom: 6,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  infoValue: {
    fontSize: 18,
    fontWeight: "700",
    color: "#fff",
  },
  infoDivider: {
    width: 1,
    backgroundColor: "#334155",
    marginHorizontal: 16,
  },
  dateRow: {
    alignItems: "center",
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: "#334155",
  },
  dateText: {
    fontSize: 13,
    color: "#64748b",
  },
  sectionsTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#fff",
    marginHorizontal: 16,
    marginBottom: 16,
  },
  section: {
    backgroundColor: "#1e293b",
    marginHorizontal: 16,
    marginBottom: 16,
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: "#334155",
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  sectionNumber: {
    fontSize: 14,
    fontWeight: "700",
    color: "#9333ea",
    backgroundColor: "rgba(147, 51, 234, 0.1)",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    marginRight: 12,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#a78bfa",
    flex: 1,
  },
  sectionContent: {
    fontSize: 15,
    color: "#cbd5e1",
    lineHeight: 24,
  },
  footer: {
    alignItems: "center",
    marginTop: 16,
    marginHorizontal: 16,
    paddingVertical: 24,
  },
  footerIcon: {
    fontSize: 32,
    marginBottom: 12,
  },
  footerText: {
    fontSize: 14,
    color: "#94a3b8",
    textAlign: "center",
    marginBottom: 4,
  },
  footerSubtext: {
    fontSize: 12,
    color: "#64748b",
    textAlign: "center",
  },
});
